services:
  - type: web
    name: peaks-baseball-api
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec ruby server.rb
    envVars:
      - key: RACK_ENV
        value: production
    plan: free 