services:
  - type: web
    name: peaks-baseball-api
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec ruby server.rb
    envVars:
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free

  - type: postgresql
    name: peaks-baseball-db
    plan: free
    ipAllowList: [] 